### PR TITLE
console: Read VNC password also from qemu.conf

### LINKED ISSUE #51: vnc password in /etc/libvirt/qemu.conf breaks cockpit vnc console
Cockpit version: 215
OS: Ubuntu server 20.04
Page:  machines, consoles tab

 I want to use both cockpit browser based vnc console and external vnc desktop viewers (krdc and remmina).

The problem is when I set the `vnc_password` in `/etc/libvirt/qemu.conf` to allow external vnc viewers to connect, it breaks the browser based vnc console.

When I disable `vnc_password` in `/etc/libvirt/qemu.conf` the browser based vnc console works but all external vnc viewers are refused.

Steps to reproduce

1. uncomment `vnc_password` in `/etc/libvirt/qemu.conf`
2. service libvirtd restart
3. goto machines console tab (shows connecting but never loads.)

screenshots
https://askubuntu.com/questions/1301001/setting-vnc-password-in-etc-libvirt-qemu-conf-breaks-cockpit-vnc-console

### PR DESCRIPTION
**Pull request by mvollmer**
This uses the "credentialsrequired" event of NoVNC, which allows us to
retrieve the password asynchronously when it is required.

Fixes #51

### CODE REVIEW

File: src/helpers.ts [hunk 1]
```diff
@@ -995,3 +995,25 @@ export function vmSupportsExternalSnapshots(config: { capabilities?: HypervisorC
...
+const VNC_PASSWORD_RX = /^[ \t]*vnc_password[ \t]*=[ \t]*"([^"\\]*(?:\\.[^"\\]*)*)"/m;
+
+export async function readQemuConf(): Promise<QemuConf> {
+    const conf: QemuConf = {
+        vnc_password: null,
+    };
+
+    const text = await cockpit.file("/etc/libvirt/qemu.conf", { superuser: "try" }).read();
+    if (!text)
+        return conf;
```
Comment (cockpituous) [inline src/helpers.ts:1012]: This added line is not executed by any test.  [Details](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-2291-f93a6539-20250821-121814-fedora-42-devel/Coverage/lcov/github-pr.diff.gcov.html)

File: test/check-machines-consoles [hunk 2]
```diff
@@ -643,6 +643,27 @@ fullscreen=0
...
+        self.createVm(name, graphics="vnc")
+
+        self.login_and_go("/machines")
+        self.waitPageInit()
+        self.waitVmRow(name)
+        self.goToVmPage(name)
+
+        # VNC viewer should be connected and should have a password
+        b.wait_visible(".vm-console-vnc canvas")
+        self.assertIn("password=on", m.execute(f"grep ^-vnc /var/log/libvirt/qemu/{name}.log"))
```
Comment (mvollmer) [inline test/check-machines-consoles:665]: It's probably better to read back the actual password via `virsh dumpxml --security-info`.

**Review by martinpitt — APPROVED** [review]
Thanks!

File: test/check-machines-consoles (hunk 2 above)
Comment (mvollmer) [reply test/check-machines-consoles:665]: Ah, no, that doesn't work: The global password is never in the XML, not even in the active one.
