### PR TITLE
Show virtual interface's TAP device

### LINKED ISSUE #1047: Show the interface name (target dev) of a network interface
Network interfaces that are attached to VMs have a tun device on the host which is automatically generated and mostly named `vnetX`, where `X` is a consecutive number.  If you want to check manually, e.g., why the device is not working correctly, you need to know the interface name. It would be great to have that information in the network interfaces row as depicted in the following mokup.

Bildschirmfoto 2023-04-25 um 17 59 02

Perhaps it could even be, similar to the source argument, a button which brings you to the device itself.

Bildschirmfoto 2023-04-25 um 17 58 40

Given the VM (domain) name and the MAC address, this information can be easily retrieved on the console, e.g., using `virsh dumpxml`, where it is given as the `dev` argument of the `target` element:

```shell
#> virsh dumpxml --xpath '//interface' "$DOMAIN" 
<interface type="bridge">
  <mac address="52:54:00:3f:2e:b8"/>
  <source bridge="bridge0"/>
  <target dev="vnet1"/>
  <model type="virtio"/>
  <alias name="net0"/>
  <address type="pci" domain="0x0000" bus="0x01" slot="0x00" function="0x0"/>
</interface>
```
and to get only the value `virsh dumpxml --xpath "//interface[mac[@address=\"$MAC\"]]/target/@dev" "$DOMAIN" | sed -nE 's/[^"]*="(.*)"/\1/p'` can be used.

Alternatively, `virsh domiflist` can also be used, which returns the value given in the first column, named `Interface`:

```shell
#> virsh domiflist "$DOMAIN" 
Interface   Type     Source    Model    MAC
------------------------------------------------------------
vnet1       bridge   bridge0   virtio   52:54:00:3f:2e:b8
```

and to get only the value, e.g., `virsh domiflist "$DOMAIN"  |  grep "$MAC" | awk '{ print $1 }'` can be used.

### PR DESCRIPTION
**Pull request by skobyda**
Network interfaces that are attached to VMs have a TAP device. Tap devices exist to facilitate virtual private networks, network tunnels...
Every virtual network interface is assigned to a TAP device, since tap device is a representation of a virtual network device on lower layers:
Tun-tap-osilayers-diagram

If you want to troubleshoot the virtual network device manually, capture its packets, etc. on those lower layers, you need to know the interface name, so we should show it in the UI:

BEFORE
Screenshot from 2023-06-22 14-53-24

AFTER
Screenshot from 2023-06-26 12-43-15

Fixes #1047

## Show virtual interface's TAP device

Network interfaces attached to VMs have a TAP device assigned, which represents the device at lower layers. Troubleshooting the virtual network device may require knowledge of the associated TAP device.

Screenshot from 2023-06-26 12-43-15

### CODE REVIEW

**Comment by skobyda** [comment]
Updated pixels

File: src/components/vm/nics/vmNicsCard.jsx [hunk 1]
```diff
@@ -105,6 +106,95 @@ VmNetworkActions.propTypes = {
...
+                return true;
+            }
+        }
+        return false;
+    };
+
+    const sourceJump = (source) => {
+        return () => {
+            if (source !== null && checkDeviceAviability(source)) {
+                cockpit.jump(`/network#/${source}`, cockpit.transport.host);
```
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:123]: These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230621-195735-af676aa5-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx [hunk 2]
```diff
@@ -105,6 +106,95 @@ VmNetworkActions.propTypes = {
...
+            </DescriptionListDescription>
+        </DescriptionListGroup>
+        <DescriptionListGroup>
+            <DescriptionListTerm>
+                {_("Port")}
+            </DescriptionListTerm>
+            <DescriptionListDescription id={`${id}-network-${networkId}-port`}>
+                {source.port}
+            </DescriptionListDescription>
+        </DescriptionListGroup>
```
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:166]: These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230621-195735-af676aa5-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

**Comment by skobyda** [comment]
Line coverage is related to the code I just moved around, not anything I added in this PR. Tests have only known flakes

**Comment by skobyda** [comment]
Ready for code review

File: src/components/vm/nics/vmNicsCard.jsx [hunk 3]
```diff
@@ -105,6 +105,55 @@ VmNetworkActions.propTypes = {
     networks: PropTypes.array.isRequired,
 };
 
+const NetworkSource = ({ network, networkId, vm, hostDevices }) => {
+    const id = vmId(vm.name);
+    const checkDeviceAviability = (network) => {
```
Comment (martinpitt) [inline src/components/vm/nics/vmNicsCard.jsx:111]: "Aviability" means checking if the device can fly, right? ✈️

The typo already exists in the moved code, it's just a funny typo.

**Review by martinpitt — DISMISSED** [review]
Thank you, LGTM! (Re-running flaked test)

Can you please update the screenshot to be less wide, and update the description for a release note?

**Comment by skobyda** [comment]
Made the IP address column consistent with the source column.
@garrett you wanted to see what it would look like with horizontal and vertical descriptionlist for this. Here some screenshots:

### Horizontal


### Horizontal Fuild


### Vertical
Screenshot from 2023-06-23 12-22-50
Screenshot from 2023-06-23 12-17-06
Screenshot from 2023-06-23 12-23-31

**Review by garrett — COMMENTED** [review]
Let's go with "horizontal fluid" for now. We don't use top-labelling much elsewhere in Cockpit.

What happens when you're in mobile? Does it "do the right thing"? If it doesn't, and vertical works, then we'll just go with that instead.

**Comment by skobyda** [comment]
@garrett Updated the PR to use fluid:

Screenshot from 2023-06-26 10-51-11

**Comment by skobyda** [comment]
@garrett Updated the PR to fluid:
Screenshot from 2023-06-26 11-03-08

**Comment by skobyda** [comment]
And this is how it looks with mobile:

Screenshot from 2023-06-26 11-04-23

File: src/components/vm/nics/vmNicsCard.jsx [hunk 4]
```diff
@@ -105,6 +107,95 @@ VmNetworkActions.propTypes = {
...
+                return true;
+            }
+        }
+        return false;
+    };
+
+    const sourceJump = (source) => {
+        return () => {
+            if (source !== null && checkDeviceAviability(source)) {
+                cockpit.jump(`/network#/${source}`, cockpit.transport.host);
```
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:124]: These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-085745-226f7c4b-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx [hunk 5]
```diff
@@ -105,6 +107,95 @@ VmNetworkActions.propTypes = {
...
+            </DescriptionListDescription>
+        </DescriptionListGroup>
+        <DescriptionListGroup>
+            <DescriptionListTerm>
+                {_("Port")}
+            </DescriptionListTerm>
+            <DescriptionListDescription id={`${id}-network-${networkId}-port`}>
+                {source.port}
+            </DescriptionListDescription>
+        </DescriptionListGroup>
```
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:167]: These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-085745-226f7c4b-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx [hunk 6]
```diff
@@ -392,28 +448,51 @@ export class VmNetworkTab extends React.Component {
...
                     return (
                         <div className='machines-listing-actions'>
-                            {deleteNICAction}
                             <Button id={`${id}-iface-${networkId}-` + (isUp ? 'unplug' : 'plug')}
                                     variant='secondary'
                                     onClick={onChangeState(network)}>
                                 {isUp ? 'Unplug' : 'Plug'}
                             </Button>
                             {editNICAction()}
+                            <Dropdown onSelect={() => this.setState({ isDropdownOpen: false })}
```
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:484]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-085745-226f7c4b-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx [hunk 7]
```diff
@@ -392,28 +448,51 @@ export class VmNetworkTab extends React.Component {
...
+                                key={id + "-action-kebab"}
+                                id={id + "-action-kebab"}
+                                toggle={<KebabToggle onToggle={(_event, isDropdownOpen) => this.setState({ isDropdownOpen })} />}
```
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:487]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-085745-226f7c4b-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

**Comment by skobyda** [comment]
Dropdown doesn't work correctly, that needs fix

**Review by garrett — APPROVED** [review]
Thanks! Looks good.

File: src/components/vm/nics/vmNicsCard.jsx (hunk 4 above)
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:124]: These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-093958-226f7c4b-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx (hunk 7 above)
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:487]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-093958-226f7c4b-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx [hunk 8]
```diff
@@ -105,6 +107,95 @@ VmNetworkActions.propTypes = {
...
+                return true;
+            }
+        }
+        return false;
+    };
+
+    const sourceJump = (source) => {
+        return () => {
+            if (source !== null && checkDeviceAvailability(source)) {
+                cockpit.jump(`/network#/${source}`, cockpit.transport.host);
```
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:124]: These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-110643-d19134c5-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx [hunk 9]
```diff
@@ -105,6 +107,95 @@ VmNetworkActions.propTypes = {
...
+            </DescriptionListDescription>
+        </DescriptionListGroup>
+        <DescriptionListGroup>
+            <DescriptionListTerm>
+                {_("Port")}
+            </DescriptionListTerm>
+            <DescriptionListDescription id={`${id}-network-${networkId}-port`}>
+                {source.port}
+            </DescriptionListDescription>
+        </DescriptionListGroup>
```
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:167]: These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-110643-d19134c5-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx (hunk 8 above)
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:124]: These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-122651-4536b036-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx (hunk 9 above)
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:167]: These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-122651-4536b036-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx (hunk 8 above)
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:124]: These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-124802-255e145d-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:124]: These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-135722-bc6440ae-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx (hunk 9 above)
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:167]: These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-135722-bc6440ae-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx [hunk 10]
```diff
@@ -281,53 +356,34 @@ export class VmNetworkTab extends React.Component {
...
+                                    </DescriptionListDescription>
+                                </DescriptionListGroup>}
+                                {ips.inet6 && <DescriptionListGroup>
+                                    <DescriptionListTerm>
+                                        {_("inet6")}
+                                    </DescriptionListTerm>
+                                    <DescriptionListDescription id={`${id}-network-${networkId}-ipv6-address`}>
+                                        {ips.inet6}
+                                    </DescriptionListDescription>
+                                </DescriptionListGroup>}
```
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:375]: These 8 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-135722-bc6440ae-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx (hunk 8 above)
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:124]: These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-152120-afec49af-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx (hunk 9 above)
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:167]: These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-152120-afec49af-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx (hunk 10 above)
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:375]: These 8 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-152120-afec49af-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

**Comment by martinpitt** [comment]
@skobyda : It's now conflicty as #1069 also changed pixels, sorry.

**Review by martinpitt — CHANGES_REQUESTED** [review]
Otherwise LGTM, just needs deconflicting pixels. Thanks!

**Review by martinpitt — APPROVED** [review]
Dakujem!

File: src/components/vm/nics/vmNicsCard.jsx (hunk 8 above)
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:124]: These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-194339-36f91e04-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx (hunk 9 above)
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:167]: These 17 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-194339-36f91e04-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx (hunk 10 above)
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:375]: These 8 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1077-20230626-194339-36f91e04-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

**Comment by skobyda** [comment]
All green, apart from one unrelated flake
