### PR TITLE
Fix false submission in dialog's form

### LINKED ISSUE #161: migration: Click "Migrate", type "qemu://foo", press Enter, the dialog goes away without an error message
The second time pressing Enter does nothing (which is fine). Clicking on "Migrate" gives me an appropriate error message.

Reported by @martinpitt on https://github.com/cockpit-project/cockpit-machines/pull/15#issuecomment-838755703

### PR DESCRIPTION
**Pull request by skobyda**
If you open a modal, select a text input and then press enter, a form
submission is trigerred, which leads to a page reloading.

Fixes #161

### CODE REVIEW

File: src/components/vm/vmCloneDialog.jsx [hunk 1]
```diff
@@ -76,7 +76,7 @@ export const CloneDialog = ({ name, connectionName, toggleModal }) => {
                    </Button>
                </>
            }>
-            <Form isHorizontal>
+            <Form onSubmit={e => e.preventDefault()} isHorizontal>
```
Comment (KKoukiou) [inline src/components/vm/vmCloneDialog.jsx:79]: Only one tiny comment. if the modal has a single value, then the primary button operation should run on submit. https://github.com/patternfly/patternfly-react/issues/5680#issuecomment-831538214

**Review by KKoukiou — CHANGES_REQUESTED** [review]

**Comment by KKoukiou** [comment]
This also fixes https://bugzilla.redhat.com/show_bug.cgi?id=1934323, to be added in the commit message.

**Review by KKoukiou — APPROVED** [review]
