### PR TITLE
Different domain's network interfaces will have different IP addresses

### LINKED ISSUE #729: Wrong ip address reported for bridge (br0)
Hi
cockpit-machines-268-1-x86_64 + cockpit-269-1-x86_64 on manjaro.

Virtual machine page is reporting a wrong ip address for a bridged connection.

Host:
br0: 192.168.1.202/24
br1: 192.168.2.1/24

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp8s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 state UP group default qlen 1000
    link/ether 60:a4:4c:09:a7:2a brd ff:ff:ff:ff:ff:ff
3: enp9s0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc fq_codel master br1 state DOWN group default qlen 1000
    link/ether 60:a4:4c:09:a7:2b brd ff:ff:ff:ff:ff:ff
4: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 36:a5:63:45:89:39 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.202/24 brd 192.168.1.255 scope global br0
       valid_lft forever preferred_lft forever
    inet6 fe80::34a5:63ff:fe45:8939/64 scope link 
       valid_lft forever preferred_lft forever
5: br1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 4e:c0:e1:da:08:f3 brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.1/24 brd 192.168.2.255 scope global br1
       valid_lft forever preferred_lft forever
    inet6 fe80::4cc0:e1ff:feda:8f3/64 scope link 
       valid_lft forever preferred_lft forever
6: vnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 state UNKNOWN group default qlen 1000
    link/ether fe:2a:14:55:1a:b2 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc2a:14ff:fe55:1ab2/64 scope link 
       valid_lft forever preferred_lft forever
7: vnet1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br1 state UNKNOWN group default qlen 1000
    link/ether fe:2a:14:32:2c:ff brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc2a:14ff:fe32:2cff/64 scope link 
       valid_lft forever preferred_lft forever
```

Guest:
br0-->en0: 192.168.1.13
br1-->en1: 192.168.2.2

```
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en1: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=463<RXCSUM,TXCSUM,TSO4,TSO6,CHANNEL_IO>
	ether xx:xx:xx:xx:xx:xx 
	inet6 fe80::1043:fbd6:79fe:ae7a%en1 prefixlen 64 secured scopeid 0x4 
	inet 192.168.2.2 netmask 0xffffff00 broadcast 192.168.2.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect <full-duplex,flow-control>
	status: active
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=463<RXCSUM,TXCSUM,TSO4,TSO6,CHANNEL_IO>
	ether xx:xx:xx:xx:xx:xx 
	inet6 fe80::42a:e25:66e3:159b%en0 prefixlen 64 secured scopeid 0x5 
	inet 192.168.1.13 netmask 0xffffff00 broadcast 192.168.1.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect <full-duplex,flow-control>
	status: active
en2: flags=8822<BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
	options=400<CHANNEL_IO>
	ether xx:xx:xx:xx:xx:xx 
	media: autoselect (<unknown type>)
	status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1380
	inet6 fe80::e781:48f8:6e8c:c4c1%utun0 prefixlen 64 scopeid 0x7 
	nd6 options=201<PERFORMNUD,DAD>
utun1: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::eecf:443d:1673:a17a%utun1 prefixlen 64 scopeid 0x8 
	nd6 options=201<PERFORMNUD,DAD>
utun2: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1000
	inet6 fe80::ce81:b1c:bd2c:69e%utun2 prefixlen 64 scopeid 0x9 
	nd6 options=201<PERFORMNUD,DAD>
```

Cockpit machines:
br

### LINKED ISSUE #1142: Cockpit doesn't show current IP of the VM
### Explain what happens

The cockpit doesn't show current IP of the VM, I have same issue in other VM distros

image

qemu-guest-agent-2.12.0-3.el7.x86_64

### Version of Cockpit

Cockpit icockpit     295-1 cockpit-machines     293-1 cockpit-pcp     295-1 cockpit-storaged     295-1

### Where is the problem in Cockpit?

Networking

### Server operating system

Arch Linux

### Server operating system version

Always on the way

### What browsers are you using?

Firefox

### System log

_No response_

### PR DESCRIPTION
**Pull request by skobyda**
Different domain's network interfaces will have different IP addresses

Until now, we would just take the output of domInterfaceAddresses, find the first valid IP address and show it next to an interface. This however doesn't take into account the fact that different network interfaces may and will have different IP addresses. Therefore we should assign correct IP address to a domain's interface based on an association with it's MAC address
    
Fixes #1142
Fixes #729

### CODE REVIEW

File: src/components/vm/nics/vmNicsCard.jsx [hunk 1]
```diff
@@ -348,29 +355,45 @@ export class VmNetworkTab extends React.Component {
...
-                value: () => {
-                    const ips = this.state.ips;
-
-                    if (!Object.keys(ips).length) {
+                value: (network, networkId) => {
+                    const ips = this.state.ips.filter(ip => ip.mac === network.mac);
+
+                    const ip = {};
+                    // If information from agent are available, it's preferred over lease/arp
+                    ips.sort((a, _) => a === "agent" ? -1 : 1).forEach(a => {
```
Comment (cockpituous) [inline src/components/vm/nics/vmNicsCard.jsx:363]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1160-20230725-142141-ae45fd2d-fedora-38-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/nics/vmNicsCard.jsx [hunk 2]
```diff
@@ -348,29 +355,45 @@ export class VmNetworkTab extends React.Component {
...
+                        // Various sources (agent,lease,arp) may have only partial information about interface
+                        // (e.g. one source may only know ipv4 address, the other may only know ipv6 address)
+                        // Therefore, look at each source to get all available information
+                        if (!ip.inet && a.ip.inet)
+                            ip.inet = a.ip.inet;
+                        if (!ip.inet6 && a.ip.inet6)
+                            ip.inet6 = a.ip.inet6;
```
Comment (martinpitt) [inline src/components/vm/nics/vmNicsCard.jsx:370]: Ugh, that's quite a dance. Is that some gap in the libvirt API?

**Review by martinpitt — APPROVED** [review]
Thank you!
