### PR TITLE
test: Drop unnecessary pool-refresh loop for iSCSI pool

### LINKED ISSUE #1284: TestMachinesStoragePools.testStoragePoolsDeletion fails in TF on Fedora-38/39/rawhide?
It cannot reproduce this locally, so this must be something with either testing farm's repo's
```
> warning: GET_STORAGE_POOL action failed for path /org/libvirt/QEMU/storagepool/_ccca9334_8442_4d1d_a579_69748eecb26b Storage pool not found: no storage pool with matching uuid 'ccca9334-8442-4d1d-a579-69748eecb26b'
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: GET_STORAGE_VOLUMES action failed for pool iscsi-pool-3 : Storage pool not found: no storage pool with matching uuid '417d0f2e-edbf-4e56-90bb-51c224672e3a'
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
> warning: One of aria-label or aria-labelledby properties should be passed when using the progress component without a title.
Wrote subVmTest1 XML to TestMachinesStoragePools-testStoragePoolsDeletion-fedora-38-localhost-22-subVmTest1.xml
Wrote subVmTest1 log to TestMachinesStoragePools-testStoragePoolsDeletion-fedora-38-localhost-22-subVmTest1.log
Traceback (most recent call last):
  File "/var/ARTIFACTS/work-storage1zzv8_0r/plans/all/storage/discover/default-0/tests/test/check-machines-storage-pools", line 1038, in testStoragePoolsDeletion
    activate=True).execute()
                   ^^^^^^^^^
  File "/var/ARTIFACTS/work-storage1zzv8_0r/plans/all/storage/discover/default-0/tests/test/check-machines-storage-pools", line 848, in execute
    self.verify()
  File "/var/ARTIFACTS/work-storage1zzv8_0r/plans/all/storage/discover/default-0/tests/test/check-machines-storage-pools", line 943, in verify
    self.test_obj.waitPoolRow(self.name, self.connection, present=False)
  File "/var/ARTIFACTS/work-storage1zzv8_0r/plans/all/storage/discover/default-0/tests/test/machineslib.py", line 108, in waitPoolRow
    b.wait_not_present(pool_row)
  File "/var/ARTIFACTS/work-storage1zzv8_0r/plans/all/storage/discover/default-0/tests/test/common/testlib.py", line 612, in wait_not_present
    self.wait_js_func('!ph_is_present', selector)
  File "/var/ARTIFACTS/work-storage1zzv8_0r/plans/all/storage/discover/default-0/tests/test/common/testlib.py", line 603, in wait_js_func
    self.wait_js_cond("%s(%s)" % (func, ','.join(map(jsquote, args))))
  File "/var/ARTIFACTS/work-storage1zzv8_0r/plans/all/storage/discover/default-0/tests/test/common/testlib.py", line 588, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/var/ARTIFACTS/work-storage1zzv8_0r/plans/all/storage/discover/default-0/tests/test/common/testlib.py", line 292, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(!ph_is_present("tbody tr[data-row-id=\"pool-iscsi-pool-3-system\"]")): condition did not become true
```

https://artifacts.dev.testing-farm.io/71dae27d-5555-4a74-b774-9c7d3303c0cc/

https://github.com/cockpit-project/cockpit-machines/pull/1282

Packages on TF:
```
+ grep -E 'libvirt|qemu'
ipxe-roms-qemu-20220210-3.git64113751.fc38.noarch
libvirt-client-9.0.0-3.fc38.x86_64
libvirt-daemon-9.0.0-3.fc38.x86_64
libvirt-daemon-config-network-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-interface-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-network-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-nodedev-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-qemu-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-storage-core-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-storage-disk-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-storage-iscsi-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-storage-iscsi-direct-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-storage-logical-9.0.0-3.fc38.x86_64
libvirt-dbus-1.4.0-7.fc38.x86_64
libvirt-glib-4.0.0-8.fc38.x86_64
libvirt-libs-9.0.0-3.fc38.x86_64
python3-libvirt-9.0.0-2.fc38.x86_64
qemu-audio-spice-7.2.6-1.fc38.x86_64
qemu-block-curl-7.2.6-1.fc38.x86_64
qemu-char-spice-7.2.6-1.fc38.x86_64
qemu-common-7.2.6-1.fc38.x86_64
qemu-device-usb-host-7.2.6-1.fc38.x86_64
qemu-device-usb-redirect-7.2.6-1.fc38.x86_64
qemu-guest-agent-7.2.6-1.fc38.x86_64
qemu-img-7.2.6-1.fc38.x86_64
qemu-kvm-core-7.2.6-1.fc38.x86_64
qemu-system-x86-core-7.2.6-1.fc38.x86_64
qemu-ui-opengl-7.2.6-1.fc38.x86_64
qemu-ui-spice-core-7.2.6-1.fc38.x86_64
```

Packages on local F38 vm with updates-testnig
```
ipxe-roms-qemu-20220210-3.git64113751.fc38.noarch
libvirt-client-9.0.0-3.fc38.x86_64
libvirt-daemon-9.0.0-3.fc38.x86_64
libvirt-daemon-config-network-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-interface-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-network-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-nodedev-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-qemu-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-storage-core-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-storage-disk-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-storage-iscsi-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-storage-iscsi-direct-9.0.0-3.fc38.x86_64
libvirt-daemon-driver-storage-logical-9.0.0-3.fc38.x86_64
libvirt-dbus-1.4.1-1.fc38.x86_64
libvirt-glib-4.0.0-8.fc38.x86_64
libvirt-libs-9.0.0-3.fc38.x86_64
python3-libvirt-9.0.0-2.fc38.x86_64
qemu-audio-spice-7.2.6-1.fc38.x86_64
qemu-block-curl-7.2.6-1.fc38.x86_64
qemu-char-spice-7.2.6-1.fc38.x86_64
qemu-common-7.2.6-1.fc38.x86_64
qemu-device-usb-host-7.2.6-1.fc38.x86_64
qemu-device-usb-redirect-7.2.6-1.fc38.x86_64
qemu-guest-agent-7.2.6-1.fc38.x86_64
qemu-img-7.2.6-1.fc38.x86_64
qemu-kvm-core-7.2.6-1.fc38.x86_64
qemu-system-x86-core-7.2.6-1.fc38.x86_64
qemu-ui-opengl-7.2.6-1.fc38.x86_64
qemu-ui-spice-core-7.2.6-1.fc38.x86_64
qemu-user-static-7.2.6-1.fc38.x86_64
qemu-user-static-aarch64-7.2.6-1.fc38.x86_64
qemu-user-static-alpha-7.2.6-1.fc38.x86_64
qemu-user-static-arm-7.2.6-1.fc38.x86_64
qemu-user-static-cris-7.2.6-1.fc38.x86_64
qemu-user-static-hexagon-7.2.6-1.fc38.x86_64
qemu-user-static-hppa-7.2.6-1.fc38.x86_64
qemu-user-static-loongarch64-7.2.6-1.fc38.x86_64
qemu-user-static-m68k-7.2.6-1.fc38.x86_64
qemu-user-static-microblaze-7.2.6-1.fc38.x86_64
qemu-user-static-mips-7.2.6-1.fc38.x86_64
qemu-user-static-nios2-7.2.6-1.fc38.x86_64
qemu-user-static-or1k-7.2.6-1.fc38.x86_64
qemu-user-static-ppc-7.2.6-1.fc38.x86_64
qemu-user-static-riscv-7.2.6-1.fc38.x86_64
qemu-user-static-s390x-7.2.6-1.fc38.x86_64
qemu-user-static-sh4-7.2.6-1.fc38.x86_64
qemu-user-static-sparc-7.2.6-1.fc38.x86_64
qemu-user-static-x86-7.2.6-1.fc38.x86_64
qemu-user-static-xtensa-7.2.6-1.fc38.x86_64
qemu-virtiofsd-7.2.6-1.fc38.x86_64
```

### PR DESCRIPTION
**Pull request by jelly**
This isn't necessary -- libvirt sends out `StoragePoolEvent.DEFINED` or
`.CREATED` when defining an iSCSI pool. We want Cockpit to pick this up
on its own, without the API poking.

This is also a race condition: The `StoragePool.Refresh` event queues an
UPDATE_ADD_STORAGE_POOL, which could run _after_ processing the
subsequent UNDEFINED event, and thus (1) logs an error, and (2) triggers
an outdated UI refresh event. There is no UI change that we could wait
for after a refresh, as we don't expect any visible state change from
the refresh, so there's no way to synchronize.

Note that this mostly just papers over a bug: If a user or something
else runs `virsh pool-refresh` at the wrong time while deleting a
storage pool, it could cause the same UI confusion. But fixing this
properly requires some bigger rearchitecting.

Fixes #1284

### CODE REVIEW

**Comment by martinpitt** [comment]
Pushed with more debug and test amplification.

**Comment by martinpitt** [comment]
Wow, succeeded everywhere except for [unrelated flakes on rawhide](https://artifacts.dev.testing-farm.io/57ea5803-31c8-416a-b60d-fdb62c8309fd/). I have a feeling that the print(virsh) changed the behaviour, and it may be a hint to what the problem is. Re-running without it.

**Comment by martinpitt** [comment]
Without the print() it again fails [lots of times](https://artifacts.dev.testing-farm.io/31dde8cd-eed2-4f6f-80e3-9a7d6da34b48/). It doesn't actually have tracing enabled, but that's not super important right now. When it fails, the virsh command confirms that the pool is gone:

```
 Name     State     Autostart   Persistent   Capacity    Allocation   Available
---------------------------------------------------------------------------------
 images   running   no          yes          48.92 GiB   2.02 GiB     46.90 GiB
```

i.e. no "iscsi-pool-3" any more. So the UI is missing an event, or a poll cycle? There was something special about storage pools, or remote/iscsi objects which causes them to not update automatically.

As I don't know about these details, let me do a test run with a higher timeout, just to see.

**Review by KKoukiou — COMMENTED** [review]
I would add some debug logs where we parse the pool events just to make sure we don't 'miss' some event.

This is done here
https://github.com/cockpit-project/cockpit-machines/blob/main/src/libvirtApi/common.js#L390

Add a log for all event types there.

If the event is missed, then it's something to debug on libvirt level. If the event comes it's probably a race condition on how we  update the redux store. In that case, I can help you debug or you can try re-fetching all pools on deletion instead of guessing the store state.

``` diff
-                store.dispatch(undefineStoragePool({ connectionName, id: objPath }));
+                // store.dispatch(undefineStoragePool({ connectionName, id: objPath }));
+                storagePoolGetAll({ connectionName })
```

**Comment by martinpitt** [comment]
Tests on 7d4c66732661877317ffbbca47b300c85c023667 look good -- all green except for some completely [unrelated rawhide failures](https://github.com/cockpit-project/cockpit-machines/runs/18304308408).

File: src/libvirtApi/common.js [hunk 1]
```diff
@@ -378,20 +378,27 @@ function startEventMonitorStoragePools(connectionName) {
...
             case Enum.VIR_STORAGE_POOL_EVENT_STARTED:
+                logDebug(`StoragePoolEvent on ${connectionName} ${objPath}: STARTED`);
                 storagePoolGet({ connectionName, id: objPath, updateOnly: true });
                 break;
             case Enum.VIR_STORAGE_POOL_EVENT_UNDEFINED:
+                logDebug(`StoragePoolEvent on ${connectionName} ${objPath}: UNDEFINED`);
                 store.dispatch(undefineStoragePool({ connectionName, id: objPath }));
                 break;
             case Enum.VIR_STORAGE_POOL_EVENT_DELETED:
+                logDebug(`StoragePoolEvent on ${connectionName} ${objPath}: DELETED`);
```
Comment (cockpituous) [inline src/libvirtApi/common.js:397]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1285-20231102-144208-464cf7a9-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/libvirtApi/common.js [hunk 2]
```diff
@@ -378,20 +378,27 @@ function startEventMonitorStoragePools(connectionName) {
...
+                // no need to handle
+                break;
```
Comment (cockpituous) [inline src/libvirtApi/common.js:399]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1285-20231102-144208-464cf7a9-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/libvirtApi/common.js [hunk 3]
```diff
@@ -378,20 +378,27 @@ function startEventMonitorStoragePools(connectionName) {
...
             default:
-                logDebug(`handle StoragePoolEvent on ${connectionName}: ignoring event ${signal}`);
+                logDebug(`handle StoragePoolEvent on ${connectionName}: ignoring event ${eventType}`);
```
Comment (cockpituous) [inline src/libvirtApi/common.js:401]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1285-20231102-144208-464cf7a9-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/libvirtApi/common.js [hunk 4]
```diff
@@ -411,15 +419,15 @@ function startEventMonitorStoragePools(connectionName) {
...
+function storagePoolStopOrUndefine(connectionName, poolPath) {
     return call(connectionName, "/org/libvirt/QEMU", "org.libvirt.Connect", "ListStoragePools", [0], { timeout, type: "u" })
             .then(objPaths => {
                 if (objPaths[0].includes(poolPath))
                     return storagePoolGet({ connectionName, id: poolPath, updateOnly: true });
                 else // Transient pool which got undefined when stopped
                     return store.dispatch(undefineStoragePool({ connectionName, id: poolPath }));
             })
-            .catch(ex => console.warn("storagePoolUpdateOrDelete action failed:", ex.toString()));
+            .catch(ex => console.warn("storagePoolStopOrUndefine action failed:", ex.toString()));
```
Comment (cockpituous) [inline src/libvirtApi/common.js:430]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1285-20231102-144208-464cf7a9-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

**Comment by martinpitt** [comment]
@KKoukiou tests are still running, but I'm hopeful, as the previous round was just with amplification+debugging. Is that approach ok for you? I'm afraid I don't have the time/skills right now to completely fix the race (that sounds like a major redesign -- I don't want to apply your `storagePoolGetAll()` suggestion from above, as it's very inefficient and likely also going to introduce more races)

**Review by KKoukiou — APPROVED** [review]

**Comment by martinpitt** [comment]
Ah, that test (and others) already [failed](https://artifacts.dev.testing-farm.io/7deb4d72-5384-46a3-967a-20a6102d6d9b/) in #1286, so doubly sure it's not a regression. I'll look at it tomorrow morning and try to get it green before doing a point release.
