### PR TITLE
Fix various issue with VM memory and storage size autodetection

### LINKED ISSUE #612: Failed to import vm with Alpine Linux 3.14 (ERROR Error: --memory 137.5367431640625: invalid literal for int() with base 10: '137.5367431640625')
Cockpit version: 
cockpit-264-1.fc35.x86_64
cockpit-machines-263-1.fc35.noarch
OS:Fedora35
Page: Vitual Machines
Chrome:Version 99.0.4844.51 (Official Build) (64-bit)

Failed to import vm with Alpine Linux 3.14 (ERROR Error: --memory 137.5367431640625: invalid literal for int() with base 10: '137.5367431640625')

Steps to reproduce
1. Prepare a vm image like cirros
2. Click "Import VM", and input needed field and "Alpine Linux 3.14" as operation system
3. Click Import
Creation of VM cirros failed 
ERROR Error: --memory 137.5367431640625: invalid literal for int() with base 10: '137.5367431640625'

### PR DESCRIPTION
**Pull request by skobyda**
Fixes #612

1. Reset memory and storage size if it cannot be autodetected for OS
This fixes the following issue: When user selects an operating system for which we know minimum required memory (e.g. centos), and then switched it to OS for which we don't know minimum memory (e.g. openBSD), old defaults are left from previous operating system, and even incorrect warning message "The selected operating system has minimum memory requirement of N MiB" could be shown.
2. The memory of a new VM, specified in MiB, cannot be a float: virt-install doesn't allow memory, supplied in MiB, to be a float number. Check if number is a integer, and if not, round up (ceil).
3. Don't use default memory for alpinelinux and hyperbola: Hyperbola and some version of alpinelinux have incorrect minimum memory
Bug report: https://gitlab.com/libosinfo/osinfo-db/-/issues/95

### CODE REVIEW

File: src/components/create-vm-dialog/createVmDialog.jsx [hunk 1]
```diff
@@ -848,7 +848,10 @@ class CreateVmModal extends React.Component {
             if (value && value.profiles)
                 stateDelta.profile = value.profiles.sort().reverse()[0];
 
-            if (value && value.minimumResources.ram) {
+            // Hyperbola and some version of alpinelinux have incorrect minimum memory
+            // https://gitlab.com/libosinfo/osinfo-db/-/issues/95
+            if (value && value.minimumResources.ram &&
+                !["alpinelinux3.15", "alpinelinux3.15", "hyperbola03"].includes(value.shortId)) {
```
Comment (martinpitt) [inline src/components/create-vm-dialog/createVmDialog.jsx:877]: What does it use instead? It seems to me that with the rounding fix this should be sufficiently unbroken. The user can still tweak it, and once it gets fixed in libosinfo, we don't have to revert the hack (especially as nothing will tell us when it gets fixed).

File: src/components/create-vm-dialog/createVmDialog.jsx [hunk 2]
```diff
@@ -817,6 +817,17 @@ class CreateVmModal extends React.Component {
         case 'storageVolume':
             this.setState({ [key]: value });
             break;
+        case 'memorySize': {
+            // virt-install doesn't allow memory, supplied in MiB, to be a float number
+            // check if number is a integer, and if not, round up (ceil)
+            let valueMiB = convertToUnit(value, this.state.memorySizeUnit, units.MiB);
+            if (valueMiB % 1 !== 0)
+                valueMiB = valueMiB.ceil();
```
Comment (martinpitt) [inline src/components/create-vm-dialog/createVmDialog.jsx:837]: Comparing floating point numbers to exact integers is unreliable in general, even if it should work for the special case of 0. Let's just drop the `if()`, and always call ceil(), it doesn't hurt. Then you can also make `valueMiB` `const`.

Also, I've never seen this being used as a method of a number object, and this doesn't work for me in node:
```
 x = 3
3
> x.ceil()
Uncaught TypeError: x.ceil is not a function
> 
```

If that works in some browsers, let's not rely on that. Please use standard [Math.ceil() function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/ceil)

File: src/components/create-vm-dialog/createVmDialog.jsx [hunk 3]
```diff
@@ -870,6 +882,8 @@ class CreateVmModal extends React.Component {
                 if (bestUnit.base1024Exponent <= 1) bestUnit = units.MiB;
                 const converted = convertToUnit(stateDelta.minimumMemory, units.B, bestUnit);
                 this.setState({ memorySizeUnit: bestUnit.name }, () => this.onValueChanged("memorySize", converted));
+            } else {
+                this.setState(getMemoryDefaults(this.props.nodeMaxMemory));
```
Comment (martinpitt) [inline src/components/create-vm-dialog/createVmDialog.jsx:886]: This makes sense, thanks! Can you please capture this in a test?

**Review by martinpitt — CHANGES_REQUESTED** [review]
Thanks!

File: src/components/create-vm-dialog/createVmDialog.jsx (hunk 1 above)
Comment (skobyda) [reply src/components/create-vm-dialog/createVmDialog.jsx:877]: I added it here because now when its broken in libosinfo, even with rounding fix, it will provide user with incorrect value for minimum resource and it would default to an incorrect value (only rounded up)
In this screenshot, the correct value according to alpine linux docs should be 128MiB, but because of a typo in libosinfo, it says 137MiB:
Screenshot from 2022-04-25 13-17-27
And I think for alpine linux it's better to show no value then incorrect one:
Screenshot from 2022-04-25 13-21-19

Comment (skobyda) [reply src/components/create-vm-dialog/createVmDialog.jsx:877]: However it's true that nothing would tell us when it gets fixed. Maybe we can add a assert in test which will warn us in the future?

Comment (martinpitt) [reply src/components/create-vm-dialog/createVmDialog.jsx:877]: I still think that proposing 137 MB is not so bad that we have to work around it. It's not wildly off, and the user can still change it. Of course fixing the rounding is important.

Comment (skobyda) [reply src/components/create-vm-dialog/createVmDialog.jsx]: Alright, dropped the workaround commit for alpine linux, now there is just rounding fix and and fix for the case when storage and memory requirements are not known

File: src/components/create-vm-dialog/createVmDialog.jsx [hunk 4]
```diff
@@ -817,6 +817,17 @@ class CreateVmModal extends React.Component {
         case 'storageVolume':
             this.setState({ [key]: value });
             break;
+        case 'memorySize': {
+            // virt-install doesn't allow memory, supplied in MiB, to be a float number
+            // check if number is a integer, and if not, round up (ceil)
+            let valueMiB = convertToUnit(value, this.state.memorySizeUnit, units.MiB);
+            if (valueMiB % 1 !== 0)
```
Comment (martinpitt) [inline src/components/create-vm-dialog/createVmDialog.jsx:837]: Please drop this `if`, just always wrap the converToUnit() into Math.ceil().

**Review by martinpitt — CHANGES_REQUESTED** [review]
Thanks! Nice test case :clap: 

Can you please rebase this to current main, so that the packit tests can run?

**Comment by martinpitt** [comment]
I just did a clean force-push to re-trigger tests (argh CI infra trouble).

[several](https://logs.cockpit-project.org/logs/pull-683-20220426-045516-a4a81be1-rhel-9-0/log.html#67) [relevant](https://logs.cockpit-project.org/logs/pull-683-20220426-045516-a4a81be1-rhel-8-6/log.html#67) failures -- the [screenshot](https://logs.cockpit-project.org/logs/pull-683-20220426-045516-a4a81be1-rhel-9-0/TestMachinesCreate-testCreateBasicValidation-rhel-9-0-127.0.0.2-2201-FAIL.png) shows invalid floating point numbers.

**Comment by skobyda** [comment]
> I just did a clean force-push to re-trigger tests (argh CI infra trouble).
> 
> [several](https://logs.cockpit-project.org/logs/pull-683-20220426-045516-a4a81be1-rhel-9-0/log.html#67) [relevant](https://logs.cockpit-project.org/logs/pull-683-20220426-045516-a4a81be1-rhel-8-6/log.html#67) failures -- the [screenshot](https://logs.cockpit-project.org/logs/pull-683-20220426-045516-a4a81be1-rhel-9-0/TestMachinesCreate-testCreateBasicValidation-rhel-9-0-127.0.0.2-2201-FAIL.png) shows invalid floating point numbers.

Ah the test showed another bug, that on some systems maximum available memory on host can also be float MiB number.
So now maximum available memory is always floored when set as default for dialog. And adjusted tests for that.

**Comment by martinpitt** [comment]
Pushed a clean rebase to run packit tests.

**Comment by martinpitt** [comment]
Pushed again to fix the first commit message.

**Review by martinpitt — APPROVED** [review]
Dakujem!
