### PR TITLE
Fix snapshots for media-less disks

### LINKED ISSUE #1433: Unable to create external snapshot on VM with cdrom device that contains no media
Using Fedora rawhide with:

cockpit-310.1-1.fc40.x86_64
cockpit-machines-306-1.fc40.noarch

I am unable to create an external snapshot if the VM has a cdrom device that contains no ISO media (see error screenshot below).  This is a likely scenario for any VM's installed from an ISO image.  

Screenshot from 2024-02-08 11-52-52

### PR DESCRIPTION
**Pull request by martinpitt**
libvirt does not currently support external snapshots for disks without media (like an empty CD-ROM drive).

Use internal snapshots for these.

Fixes #1433

### CODE REVIEW

File: src/helpers.js [hunk 1]
```diff
@@ -901,9 +901,10 @@ export function vmSupportsExternalSnapshots(config, vm, storagePools) {
 
     // Currently external snapshots works only for disks where we can specify a local path of a newly created disk snapshot file
     // This rules out all disks which are not file-based, or pool-based where pool is of type "dir"
+    // or media-less disks
     const supportedPools = storagePools.filter(pool => pool.type === "dir" && pool.connectionName === vm.connectionName);
     if (!disks.every(disk =>
-        disk.type === "file" ||
+        (disk.type === "file" && disk.source?.file) ||
```
Comment (cockpituous) [inline src/helpers.js:907]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1440-20240212-085014-bd28d833-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

**Review by jelly — APPROVED** [review]
