### PR TITLE
Fix crash on checking for hw virtualization

### LINKED ISSUE #1523: wait_in_text("body", "Virtual machines") failed in aarch64
When running automation with aarch64, there will be a "raise T" in waitPageInit -> self.browser.wait_in_text("body", "Virtual machines"). Also, add some details from the automation log
{"exceptionId":1,"text":"Uncaught (in promise)","lineNumber":696,"columnNumber":9103,"scriptId":"36","url":"http://10.6.6.171:9090/cockpit/@localhost/machines/index.js","stackTrace":{"callFrames":[{"functionName":"","scriptId":"36","url":"http://10.6.6.171:9090/cockpit/@localhost/machines/index.js","lineNumber":696,"columnNumber":9103}]},"exception":{"type":"object","className":"T","description":"T","objectId":"3545638390102327573.8.1","preview":{"type":"object","description":"T","overflow":false,"properties":[{"name":"problem","type":"object","value":"null","subtype":"null"},{"name":"exit_status","type":"number","value":"1"},{"name":"exit_signal","type":"object","value":"null","subtype":"null"},{"name":"message","type":"string","value":""},{"name":"toString","type":"function","value":""}]}},"executionContextId":8}

### PR DESCRIPTION
**Pull request by martinpitt**
`virt-host-validate` does not actually include "Checking for hardware virtualization" on ARM, so the page crashes due to the grep exiting with non-zero.

While at it, restrict the checks to QEMU. We aren't interested in LXC or other hypervisors.

Thanks to @yunmingyang for debugging this!

Fixes #1523

### CODE REVIEW

File: src/app.jsx [hunk 1]
```diff
@@ -104,9 +104,14 @@ export const App = () => {
...
     useEffect(() => {
         (async () => {
-            const hardwareVirtCheck = await cockpit.script("virt-host-validate | grep 'Checking for hardware virtualization'");
-
-            setVirtualizationEnabled(hardwareVirtCheck.includes('PASS'));
+            try {
+                const hardwareVirtCheck = await cockpit.script(
+                    "virt-host-validate qemu | grep 'Checking for hardware virtualization'");
+                setVirtualizationEnabled(hardwareVirtCheck.includes('PASS'));
+            } catch (ex) {
```
Comment (cockpituous) [inline src/app.jsx:111]: This added line is not executed by any test.

File: src/app.jsx [hunk 2]
```diff
@@ -104,9 +104,14 @@ export const App = () => {
...
+                // That line doesn't exist on some architectures, so the grep may fail
+                console.debug("Failed to check for hardware virtualization:", ex);
```
Comment (cockpituous) [inline src/app.jsx:113]: This added line is not executed by any test.

**Comment by martinpitt** [comment]
[this failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1543-19755899-20240408-074544-fedora-39/log.html) is unrelated, I also just saw it in https://github.com/cockpit-project/bots/pull/6184 . Presumably we just need to wait with the pixel check until the button becomes enabled?
