### PR TITLE
Re-write and cleanup disk add dialog

### LINKED ISSUE #1275: AddDiskModalBody does recursive setState()
The Add disk dialog has [lots of instances](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1274-20231027-124307-1f1884f1-fedora-38-devel/log.html#59) of

> error: Warning: An update (setState, replaceState, or forceUpdate) was scheduled from inside an update function. Update functions should be pure, with zero side-effects. Consider using componentDidUpdate or a callback.%s 
>    at AddDiskModalBody (http://127.0.0.2:9591/cockpit/@localhost/machines/index.js:133728:7)
>    at WithDialogs (http://127.0.0.2:9591/cockpit/@localhost/machines/index.js:120550:24)
>    at VmDetailsPage (http://127.0.0.2:9591/cockpit/@localhost/machines/index.js:161096:5)
>    at AppActive (http://127.0.0.2:9591/cockpit/@localhost/machines/index.js:163591:7)
>    at App (http://127.0.0.2:9591/cockpit/@localhost/machines/index.js:163541:81)

This is because the whole state management there is very hackish and convoluted:

 1. `onValueChanged('existingVolumeName', ...)` calls `this.setState(this.existingVolumeNameDelta())`
 2. `existingVolumeNameDelta()` calls `this.onValueChanged("device", ...)`
 3. `onValueChanged('device', ...)` calls `setState()` a lot, leading to the recursion.

It is really hard to follow that code. I propose to split up `onValueChanged`, make existingVolumeNameDelta() pure and *always* just return a state delta that the caller has to handle.

### PR DESCRIPTION
**Pull request by KKoukiou**
Fixes #1275

### CODE REVIEW

File: src/components/vm/disks/diskAdd.jsx [hunk 1]
```diff
@@ -182,25 +182,21 @@ const AdditionalOptions = ({ cacheMode, device, idPrefix, onValueChanged, busTyp
     // https://libvirt.org/formatdomain.html#hard-drives-floppy-disks-cdroms
     const serialLength = busType === "scsi" ? 36 : 20;
 
-    const setSerialHelper = useCallback(value => {
-        const clearedSerial = clearSerial(value);
+    useEffect(() => {
+        const clearedSerial = clearSerial(serial);
 
-        if (value !== clearedSerial)
+        if (serial !== clearedSerial) {
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:188]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231109-142627-1ac1b404-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 2]
```diff
@@ -182,25 +182,21 @@ const AdditionalOptions = ({ cacheMode, device, idPrefix, onValueChanged, busTyp
...
             // Show the message once triggerred and leave it around as reminder
             setShowAllowedCharactersMessage(true);
+            onValueChanged('serial', clearedSerial);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:191]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231109-142627-1ac1b404-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 3]
```diff
@@ -244,7 +240,7 @@ const AdditionalOptions = ({ cacheMode, device, idPrefix, onValueChanged, busTyp
                         aria-label={_("serial number")}
                         className="ct-monospace"
                         value={serial}
-                        onChange={(_, value) => setSerialHelper(value)} />
+                        onChange={(_, value) => onValueChanged("serial", value)} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:243]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231109-142627-1ac1b404-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 4]
```diff
@@ -365,104 +361,92 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+const sortFunction = (poolA, poolB) => poolA.name.localeCompare(poolB.name);
+
+export const AddDiskModalBody = ({ disk, idPrefix, isMediaInsertion, vm, vms, supportedDiskBusTypes }) => {
+    const [addDiskInProgress, setAddDiskInProgress] = useState(false);
+    const [customDiskVerificationFailed, setCustomDiskVerificationFailed] = useState(false);
+    const [customDiskVerificationMessage, setCustomDiskVerificationMessage] = useState(null);
+    const [dialogError, setDialogError] = useState(null);
+    const [dialogErrorDetail, setDialogErrorDetail] = useState(null);
+    const [dialogLoading, setDialogLoading] = useState(true);
+    const [mode, setMode] = useState(isMediaInsertion ? CUSTOM_PATH : CREATE_NEW);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:373]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231109-142627-1ac1b404-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 5]
```diff
@@ -365,104 +361,92 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
         const validationFailed = {};
 
-        if (this.state.mode !== CUSTOM_PATH && !this.state.storagePoolName)
+        if (mode !== CUSTOM_PATH && !storagePoolName)
             validationFailed.storagePool = _("Please choose a storage pool");
 
-        if (this.state.mode === CUSTOM_PATH && this.state.customDiskVerificationFailed)
-            validationFailed.customPath = this.state.customDiskVerificationMessage;
+        if (mode === CUSTOM_PATH && customDiskVerificationFailed)
+            validationFailed.customPath = customDiskVerificationMessage;
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:428]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231109-142627-1ac1b404-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 6]
```diff
@@ -479,70 +463,70 @@ export class AddDiskModalBody extends React.Component {
...
+                if (poolName) {
+                    setMode(
+                        value,
+                        () => setDiskParams(diskParams => ({
+                            ...diskParams,
+                            ...initialDiskParams,
+                            ...existingVolumeNameDelta(getDefaultVolumeName(poolName, storagePools, vm), storagePoolName)
+                        })
+                        ));
+                    return;
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:507]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231109-142627-1ac1b404-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 7]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+const sortFunction = (poolA, poolB) => poolA.name.localeCompare(poolB.name);
+
+export const AddDiskModalBody = ({ disk, idPrefix, isMediaInsertion, vm, vms, supportedDiskBusTypes }) => {
+    const [customDiskVerificationFailed, setCustomDiskVerificationFailed] = useState(false);
+    const [customDiskVerificationMessage, setCustomDiskVerificationMessage] = useState(null);
+    const [dialogError, setDialogError] = useState(null);
+    const [dialogErrorDetail, setDialogErrorDetail] = useState(null);
+    const [dialogLoading, setDialogLoading] = useState(true);
+    const [diskParams, setDiskParams] = useState({});
+    const [mode, setMode] = useState(isMediaInsertion ? CUSTOM_PATH : CREATE_NEW);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:370]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 8]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
         // Refresh storage volume list before displaying the dialog.
         // There are recently no Libvirt events for storage volumes and polling is ugly.
         // https://bugzilla.redhat.com/show_bug.cgi?id=1578836
-        storagePoolGetAll({ connectionName: this.props.vm.connectionName })
-                .then(() => this.setState({ dialogLoading: false, ...this.initialState }))
-                .catch(exc => this.dialogErrorSet(_("Storage pools could not be fetched"), exc.message));
-    }
+        storagePoolGetAll({ connectionName: vm.connectionName })
+                .always(() => setDialogLoading(false))
+                .catch(exc => dialogErrorSet(_("Storage pools could not be fetched"), exc.message));
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:411]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 9]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
             // All pool types apart from 'disk' have either 'raw' or 'qcow2' format
-            if (currentPool && prevPool && ((currentPool.type == 'disk' && prevPool.type != 'disk') || (currentPool.type != 'disk' && prevPool.type == 'disk'))) {
-                // use onValueChange instead of setState in order to perform subsequent state change logic
-                this.onValueChanged('format', getDefaultVolumeFormat(value));
+            const prevPool = currentPoolRef.current;
+            if ((diskParams.storagePool?.type == 'disk' && prevPool?.type != 'disk') || (diskParams.storagePool?.type != 'disk' && prevPool?.type == 'disk')) {
+                prevPool.current = diskParams.storagePool;
+                setDiskParams(diskParams => ({
+                    ...diskParams,
+                    format: getDefaultVolumeFormat(diskParams.storagePool?.name),
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:490]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 10]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+        if (file) {
+            setVerificationInProgress(true);
+            cockpit.spawn(["head", "--bytes=16", file], { binary: true, err: "message", superuser: "try" })
+                    .then(file_header => {
+                        let format = "";
+
+                        // https://git.qemu.org/?p=qemu.git;a=blob;f=docs/interop/qcow2.txt
+                        if (file_header[0] == 81 && file_header[1] == 70 &&
+                            file_header[2] == 73 && file_header[3] == 251) {
+                            format = "qcow2";
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:518]: These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 11]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                            // All zeros, no backing file offset
+                            if (file_header.slice(8).every(bytes => bytes === 0)) {
+                                setCustomDiskVerificationFailed(false);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:521]: These 2 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 12]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
                             } else {
-                                format = "raw";
-                                this.setState({ customDiskVerificationFailed: false, format });
+                                setCustomDiskVerificationFailed(true);
+                                setCustomDiskVerificationMessage(_("Importing an image with a backing file is unsupported"));
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:524]: These 2 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 13]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+    let defaultBody;
+    if (dialogLoading) {
+        defaultBody = (
+            <Bullseye>
+                <Spinner />
+            </Bullseye>
+        );
+    } else if (isMediaInsertion) {
+        defaultBody = (
+            <Form onSubmit={e => e.preventDefault()} isHorizontal>
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:573]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 14]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                <FormGroup fieldId={`${idPrefix}-source`}
+                           id={`${idPrefix}-source-group`}
+                           label={_("Source")} isInline hasNoPaddingTop>
+                    <Radio id={`${idPrefix}-custompath`}
+                           name="source"
+                           label={_("Custom path")}
+                           isChecked={mode === CUSTOM_PATH}
+                           onChange={() => onValueChanged('mode', CUSTOM_PATH)} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:581]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 15]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                    <Radio id={`${idPrefix}-useexisting`}
+                           name="source"
+                           label={_("Use existing")}
+                           isChecked={mode === USE_EXISTING}
+                           onChange={() => onValueChanged('mode', USE_EXISTING)} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:586]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 16]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                </FormGroup>
+                {mode === USE_EXISTING && (
+                    <UseExistingDisk idPrefix={`${idPrefix}-existing`}
+                                     onValueChanged={onValueChanged}
+                                     storagePoolName={storagePoolName}
+                                     existingVolumeName={diskParams.existingVolumeName}
+                                     validationFailed={validationFailed}
+                                     vmStoragePools={storagePools}
+                                     vms={vms}
+                                     vm={vm} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:596]: These 8 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 17]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                                onValueChanged={onValueChanged}
+                                hideDeviceRow
+                                validationFailed={validationFailed} />
+                )}
+            </Form>
+        );
+    } else {
+        defaultBody = (
+            <>
+                <Form onSubmit={e => e.preventDefault()} isHorizontal>
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:609]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 18]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                    <FormGroup fieldId={`${idPrefix}-source`}
+                               id={`${idPrefix}-source-group`}
+                               label={_("Source")} isInline hasNoPaddingTop>
+                        <Radio id={`${idPrefix}-createnew`}
+                               name="source"
+                               label={_("Create new")}
+                               isChecked={mode === CREATE_NEW}
+                               onChange={() => onValueChanged('mode', CREATE_NEW)} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:617]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 19]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+            </>
+        );
     }
 
-    dialogErrorSet(text, detail) {
-        this.setState({ dialogError: text, dialogErrorDetail: detail });
-    }
+    return (
+        <Modal position="top" variant="medium" id={`${idPrefix}-dialog-modal-window`} isOpen onClose={Dialogs.close}
+               title={isMediaInsertion ? _("Insert disc media") : _("Add disk")}
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:676]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 20]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
-        const Dialogs = this.context;
-        const close = Dialogs.close;
-        const { vm } = this.state;
-        const { disk } = this.props;
+    const validateParams = () => {
+        const validationFailed = {};
+        const storagePoolType = diskParams.storagePool?.type;
+
+        if (mode !== CUSTOM_PATH && !storagePoolName)
+            validationFailed.storagePool = _("Please choose a storage pool");
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:728]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 21]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+
+        if (mode === CUSTOM_PATH && customDiskVerificationFailed)
+            validationFailed.customPath = customDiskVerificationMessage;
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:731]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 22]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+            if (poolTypesNotSupportingVolumeCreation.includes(storagePoolType)) {
+                validationFailed.storagePool = cockpit.format(_("Pool type $0 does not support volume creation"), storagePoolType);
+            }
+            const poolCapacity = parseFloat(convertToUnit(storagePools.find(pool => pool.name == storagePoolName).capacity, units.B, diskParams.unit));
+            if (diskParams.size > poolCapacity) {
+                validationFailed.size = cockpit.format(_("Storage volume size must not exceed the storage pool's capacity ($0 $1)"), poolCapacity.toFixed(2), diskParams.unit);
+            }
+        } else if (mode === USE_EXISTING) {
+            if (mode !== CUSTOM_PATH && !diskParams.existingVolumeName)
+                validationFailed.existingVolumeName = _("Please choose a volume");
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:746]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 23]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+    const onInsertClicked = () => {
         return domainInsertDisk({
             connectionName: vm.connectionName,
             vmName: vm.name,
             target: disk.target,
-            diskType: this.state.mode === CUSTOM_PATH ? "file" : "volume",
-            file: this.state.file,
-            poolName: this.state.storagePoolName,
-            volumeName: this.state.existingVolumeName,
+            diskType: mode === CUSTOM_PATH ? "file" : "volume",
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:757]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 24]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                    if (mode !== CUSTOM_PATH && volume.format === "raw" && isVolumeUsed[diskParams.existingVolumeName]) {
+                        isVolumeUsed[diskParams.existingVolumeName].forEach(vmName => {
                             const vm = vms.find(vm => vm.name === vmName);
-                            const diskTarget = getStorageVolumeDiskTarget(vm, storagePool, this.state.existingVolumeName);
+                            const diskTarget = getStorageVolumeDiskTarget(vm, storagePool, diskParams.existingVolumeName);
 
                             promises.push(
                                 domainUpdateDiskAttributes({ connectionName: vm.connectionName, objPath: vm.id, readonly: false, shareable: true, target: diskTarget })
-                                        .catch(exc => this.dialogErrorSet(_("Disk settings could not be saved"), exc.message))
+                                        .catch(exc => dialogErrorSet(_("Disk settings could not be saved"), exc.message))
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:820]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 25]
```diff
@@ -365,511 +358,511 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+    return (
+        <>
+            <Button id={`${idPrefix}-dialog-add`}
+                    variant='primary'
+                    isLoading={addDiskInProgress || verificationInProgress}
+                    isDisabled={addDiskInProgress || verificationInProgress || dialogLoading ||
+                                (storagePools.length == 0 && mode != CUSTOM_PATH) ||
+                                (mode == CUSTOM_PATH && diskParams.device === "disk" && customDiskVerificationFailed)}
+                    onClick={onClick}>
+                {isMediaInsertion ? _("Insert") : _("Add")}
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:861]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231110-154059-d19bea72-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 26]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+const sortFunction = (poolA, poolB) => poolA.name.localeCompare(poolB.name);
+
+export const AddDiskModalBody = ({ disk, idPrefix, isMediaInsertion, vm, vms, supportedDiskBusTypes }) => {
+    const [customDiskVerificationFailed, setCustomDiskVerificationFailed] = useState(false);
+    const [customDiskVerificationMessage, setCustomDiskVerificationMessage] = useState(null);
+    const [dialogError, setDialogError] = useState(null);
+    const [dialogErrorDetail, setDialogErrorDetail] = useState(null);
+    const [dialogLoading, setDialogLoading] = useState(true);
+    const [diskParams, setDiskParams] = useState({});
+    const [mode, setMode] = useState(isMediaInsertion ? CUSTOM_PATH : CREATE_NEW);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:370]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 27]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
-    }
-
-    validateParams() {
-        const validationFailed = {};
-
-        if (this.state.mode !== CUSTOM_PATH && !this.state.storagePoolName)
-            validationFailed.storagePool = _("Please choose a storage pool");
+        storagePoolGetAll({ connectionName: vm.connectionName })
+                .always(() => setDialogLoading(false))
+                .catch(exc => dialogErrorSet(_("Storage pools could not be fetched"), exc.message));
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:408]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 28]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+            newBus = newBus || "virtio";
+        }
+
+        setDiskParams(diskParams => ({ ...diskParams, busType: newBus }));
+    }, [diskParams.device, vm.disks]);
+
+    useEffect(() => {
+        // Initial state settings and follow up state updates after 'busType' is changed
+        const existingTargets = Object.getOwnPropertyNames(vm.disks);
+        const availableTarget = isMediaInsertion ? disk.target : getNextAvailableTarget(existingTargets, diskParams.busType);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:468]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 29]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
-
-            if (this.state.mode === USE_EXISTING) { // user changed pool
-                // use onValueChange instead of setState in order to perform subsequent state change logic
-                this.onValueChanged('existingVolumeName', getDefaultVolumeName(value, storagePools, vm));
+            const prevPool = currentPoolRef.current;
+            if ((diskParams.storagePool?.type == 'disk' && prevPool?.type != 'disk') || (diskParams.storagePool?.type != 'disk' && prevPool?.type == 'disk')) {
+                prevPool.current = diskParams.storagePool;
+                setDiskParams(diskParams => ({
+                    ...diskParams,
+                    format: getDefaultVolumeFormat(diskParams.storagePool?.name),
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:484]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 30]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+    let defaultBody;
+    if (dialogLoading) {
+        defaultBody = (
+            <Bullseye>
+                <Spinner />
+            </Bullseye>
+        );
+    } else if (isMediaInsertion) {
+        defaultBody = (
+            <Form onSubmit={e => e.preventDefault()} isHorizontal>
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:567]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 31]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                <FormGroup fieldId={`${idPrefix}-source`}
+                           id={`${idPrefix}-source-group`}
+                           label={_("Source")} isInline hasNoPaddingTop>
+                    <Radio id={`${idPrefix}-custompath`}
+                           name="source"
+                           label={_("Custom path")}
+                           isChecked={mode === CUSTOM_PATH}
+                           onChange={() => onValueChanged('mode', CUSTOM_PATH)} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:575]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 32]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                    <Radio id={`${idPrefix}-useexisting`}
+                           name="source"
+                           label={_("Use existing")}
+                           isChecked={mode === USE_EXISTING}
+                           onChange={() => onValueChanged('mode', USE_EXISTING)} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:580]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 33]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                </FormGroup>
+                {mode === USE_EXISTING && (
+                    <UseExistingDisk idPrefix={`${idPrefix}-existing`}
+                                     onValueChanged={onValueChanged}
+                                     storagePoolName={storagePoolName}
+                                     existingVolumeName={diskParams.existingVolumeName}
+                                     validationFailed={validationFailed}
+                                     vmStoragePools={storagePools}
+                                     vms={vms}
+                                     vm={vm} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:590]: These 8 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 34]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                                onValueChanged={onValueChanged}
+                                hideDeviceRow
+                                validationFailed={validationFailed} />
+                )}
+            </Form>
+        );
+    } else {
+        defaultBody = (
+            <>
+                <Form onSubmit={e => e.preventDefault()} isHorizontal>
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:603]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 35]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                    <FormGroup fieldId={`${idPrefix}-source`}
+                               id={`${idPrefix}-source-group`}
+                               label={_("Source")} isInline hasNoPaddingTop>
+                        <Radio id={`${idPrefix}-createnew`}
+                               name="source"
+                               label={_("Create new")}
+                               isChecked={mode === CREATE_NEW}
+                               onChange={() => onValueChanged('mode', CREATE_NEW)} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:611]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 36]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+            </>
+        );
     }
 
-    dialogErrorSet(text, detail) {
-        this.setState({ dialogError: text, dialogErrorDetail: detail });
-    }
+    return (
+        <Modal position="top" variant="medium" id={`${idPrefix}-dialog-modal-window`} isOpen onClose={Dialogs.close}
+               title={isMediaInsertion ? _("Insert disc media") : _("Add disk")}
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:670]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 37]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+        const validationFailed = {};
+        const storagePoolType = diskParams.storagePool?.type;
 
-    onInsertClicked() {
-        const Dialogs = this.context;
-        const close = Dialogs.close;
-        const { vm } = this.state;
-        const { disk } = this.props;
+        if (mode !== CUSTOM_PATH && !storagePoolName)
+            validationFailed.storagePool = _("Please choose a storage pool");
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:721]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 38]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+
+        if (mode === CUSTOM_PATH && customDiskVerificationFailed)
+            validationFailed.customPath = customDiskVerificationMessage;
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:724]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 39]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+            if (poolTypesNotSupportingVolumeCreation.includes(storagePoolType)) {
+                validationFailed.storagePool = cockpit.format(_("Pool type $0 does not support volume creation"), storagePoolType);
+            }
+            const poolCapacity = parseFloat(convertToUnit(storagePools.find(pool => pool.name == storagePoolName).capacity, units.B, diskParams.unit));
+            if (diskParams.size > poolCapacity) {
+                validationFailed.size = cockpit.format(_("Storage volume size must not exceed the storage pool's capacity ($0 $1)"), poolCapacity.toFixed(2), diskParams.unit);
+            }
+        } else if (mode === USE_EXISTING) {
+            if (mode !== CUSTOM_PATH && !diskParams.existingVolumeName)
+                validationFailed.existingVolumeName = _("Please choose a volume");
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:739]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 40]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
         return domainInsertDisk({
             connectionName: vm.connectionName,
             vmName: vm.name,
-            target: disk.target,
-            diskType: this.state.mode === CUSTOM_PATH ? "file" : "volume",
-            file: this.state.file,
-            poolName: this.state.storagePoolName,
-            volumeName: this.state.existingVolumeName,
+            target: diskParams.target,
+            diskType: mode === CUSTOM_PATH ? "file" : "volume",
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:750]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 41]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                    if (mode !== CUSTOM_PATH && volume.format === "raw" && isVolumeUsed[diskParams.existingVolumeName]) {
+                        isVolumeUsed[diskParams.existingVolumeName].forEach(vmName => {
                             const vm = vms.find(vm => vm.name === vmName);
-                            const diskTarget = getStorageVolumeDiskTarget(vm, storagePool, this.state.existingVolumeName);
+                            const diskTarget = getStorageVolumeDiskTarget(vm, storagePool, diskParams.existingVolumeName);
 
                             promises.push(
                                 domainUpdateDiskAttributes({ connectionName: vm.connectionName, objPath: vm.id, readonly: false, shareable: true, target: diskTarget })
-                                        .catch(exc => this.dialogErrorSet(_("Disk settings could not be saved"), exc.message))
+                                        .catch(exc => dialogErrorSet(_("Disk settings could not be saved"), exc.message))
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:814]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 42]
```diff
@@ -365,511 +358,507 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+    return (
+        <>
+            <Button id={`${idPrefix}-dialog-add`}
+                    variant='primary'
+                    isLoading={addDiskInProgress || verificationInProgress}
+                    isDisabled={addDiskInProgress || verificationInProgress || dialogLoading ||
+                                (storagePools.length == 0 && mode != CUSTOM_PATH) ||
+                                (mode == CUSTOM_PATH && diskParams.device === "disk" && customDiskVerificationFailed)}
+                    onClick={onClick}>
+                {isMediaInsertion ? _("Insert") : _("Add")}
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:857]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231113-155652-97d90b8c-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 43]
```diff
@@ -365,511 +359,510 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+const sortFunction = (poolA, poolB) => poolA.name.localeCompare(poolB.name);
+
+export const AddDiskModalBody = ({ disk, idPrefix, isMediaInsertion, vm, vms, supportedDiskBusTypes }) => {
+    const [customDiskVerificationFailed, setCustomDiskVerificationFailed] = useState(false);
+    const [customDiskVerificationMessage, setCustomDiskVerificationMessage] = useState(null);
+    const [dialogError, setDialogError] = useState(null);
+    const [dialogErrorDetail, setDialogErrorDetail] = useState(null);
+    const [dialogLoading, setDialogLoading] = useState(true);
+    const [diskParams, setDiskParams] = useState({});
+    const [mode, setMode] = useState(isMediaInsertion ? CUSTOM_PATH : CREATE_NEW);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:371]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231114-134752-e3097bd0-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 44]
```diff
@@ -365,511 +359,510 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
-    }
-
-    validateParams() {
-        const validationFailed = {};
-
-        if (this.state.mode !== CUSTOM_PATH && !this.state.storagePoolName)
-            validationFailed.storagePool = _("Please choose a storage pool");
+        storagePoolGetAll({ connectionName: vm.connectionName })
+                .always(() => setDialogLoading(false))
+                .catch(exc => dialogErrorSet(_("Storage pools could not be fetched"), exc.message));
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:407]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231114-134752-e3097bd0-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 45]
```diff
@@ -365,511 +359,510 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
-    onValueChanged(key, value) {
-        let stateDelta = {};
-        const { storagePools, vm } = this.state;
+        setDiskParams(diskParams => ({ ...diskParams, busType: newBus }));
+    }, [diskParams.device, vm.disks]);
+
+    useEffect(() => {
+        // Initial state settings and follow up state updates after 'busType' is changed
+        const existingTargets = Object.getOwnPropertyNames(vm.disks);
+        const availableTarget = isMediaInsertion ? disk.target : getNextAvailableTarget(existingTargets, diskParams.busType);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:467]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231114-134752-e3097bd0-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 46]
```diff
@@ -365,511 +359,510 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
-
-            if (this.state.mode === USE_EXISTING) { // user changed pool
-                // use onValueChange instead of setState in order to perform subsequent state change logic
-                this.onValueChanged('existingVolumeName', getDefaultVolumeName(value, storagePools, vm));
+            const prevPool = currentPoolRef.current;
+            if ((diskParams.storagePool?.type == 'disk' && prevPool?.type != 'disk') || (diskParams.storagePool?.type != 'disk' && prevPool?.type == 'disk')) {
+                prevPool.current = diskParams.storagePool;
+                setDiskParams(diskParams => ({
+                    ...diskParams,
+                    format: getDefaultVolumeFormat(diskParams.storagePool?.name),
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:483]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231114-134752-e3097bd0-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 47]
```diff
@@ -365,511 +359,510 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+    let defaultBody;
+    if (dialogLoading) {
+        defaultBody = (
+            <Bullseye>
+                <Spinner />
+            </Bullseye>
+        );
+    } else if (isMediaInsertion) {
+        defaultBody = (
+            <Form onSubmit={e => e.preventDefault()} isHorizontal>
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:599]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231114-134752-e3097bd0-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 48]
```diff
@@ -365,511 +359,510 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                <FormGroup fieldId={`${idPrefix}-source`}
+                           id={`${idPrefix}-source-group`}
+                           label={_("Source")} isInline hasNoPaddingTop>
+                    <Radio id={`${idPrefix}-custompath`}
+                           name="source"
+                           label={_("Custom path")}
+                           isChecked={mode === CUSTOM_PATH}
+                           onChange={() => onValueChanged('mode', CUSTOM_PATH)} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:607]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231114-134752-e3097bd0-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 49]
```diff
@@ -365,511 +359,510 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                    <Radio id={`${idPrefix}-useexisting`}
+                           name="source"
+                           label={_("Use existing")}
+                           isChecked={mode === USE_EXISTING}
+                           onChange={() => onValueChanged('mode', USE_EXISTING)} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:612]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231114-134752-e3097bd0-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 50]
```diff
@@ -365,511 +359,510 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                </FormGroup>
+                {mode === USE_EXISTING && (
+                    <UseExistingDisk idPrefix={`${idPrefix}-existing`}
+                                     onValueChanged={onValueChanged}
+                                     storagePoolName={storagePoolName}
+                                     existingVolumeName={diskParams.existingVolumeName}
+                                     validationFailed={validationFailed}
+                                     vmStoragePools={storagePools}
+                                     vms={vms}
+                                     vm={vm} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:622]: These 8 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231114-134752-e3097bd0-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 51]
```diff
@@ -365,511 +359,510 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                                onValueChanged={onValueChanged}
+                                hideDeviceRow
+                                validationFailed={validationFailed} />
+                )}
+            </Form>
+        );
+    } else {
+        defaultBody = (
+            <>
+                <Form onSubmit={e => e.preventDefault()} isHorizontal>
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:635]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231114-134752-e3097bd0-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 52]
```diff
@@ -365,511 +359,510 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
     }
 
-    onInsertClicked() {
-        const Dialogs = this.context;
-        const close = Dialogs.close;
-        const { vm } = this.state;
-        const { disk } = this.props;
+    return (
+        <Modal position="top" variant="medium" id={`${idPrefix}-dialog-modal-window`} isOpen onClose={Dialogs.close}
+               title={isMediaInsertion ? _("Insert disc media") : _("Add disk")}
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:702]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231114-134752-e3097bd0-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 53]
```diff
@@ -365,511 +359,510 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
         return domainInsertDisk({
             connectionName: vm.connectionName,
             vmName: vm.name,
-            target: disk.target,
-            diskType: this.state.mode === CUSTOM_PATH ? "file" : "volume",
-            file: this.state.file,
-            poolName: this.state.storagePoolName,
-            volumeName: this.state.existingVolumeName,
+            target: diskParams.target,
+            diskType: mode === CUSTOM_PATH ? "file" : "volume",
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:755]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231114-134752-e3097bd0-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 54]
```diff
@@ -365,511 +359,510 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                    if (mode !== CUSTOM_PATH && volume.format === "raw" && isVolumeUsed[diskParams.existingVolumeName]) {
+                        isVolumeUsed[diskParams.existingVolumeName].forEach(vmName => {
                             const vm = vms.find(vm => vm.name === vmName);
-                            const diskTarget = getStorageVolumeDiskTarget(vm, storagePool, this.state.existingVolumeName);
+                            const diskTarget = getStorageVolumeDiskTarget(vm, storagePool, diskParams.existingVolumeName);
 
                             promises.push(
                                 domainUpdateDiskAttributes({ connectionName: vm.connectionName, objPath: vm.id, readonly: false, shareable: true, target: diskTarget })
-                                        .catch(exc => this.dialogErrorSet(_("Disk settings could not be saved"), exc.message))
+                                        .catch(exc => dialogErrorSet(_("Disk settings could not be saved"), exc.message))
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:819]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231114-134752-e3097bd0-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 55]
```diff
@@ -365,511 +359,510 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+    return (
+        <>
+            <Button id={`${idPrefix}-dialog-add`}
+                    variant='primary'
+                    isLoading={addDiskInProgress || verificationInProgress}
+                    isDisabled={addDiskInProgress || verificationInProgress || dialogLoading ||
+                                (storagePools.length == 0 && mode != CUSTOM_PATH) ||
+                                (validate && Object.keys(validationFailed).length > 0)}
+                    onClick={onClick}>
+                {isMediaInsertion ? _("Insert") : _("Add")}
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:861]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231114-134752-e3097bd0-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 56]
```diff
@@ -365,511 +359,505 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+const sortFunction = (poolA, poolB) => poolA.name.localeCompare(poolB.name);
+
+export const AddDiskModalBody = ({ disk, idPrefix, isMediaInsertion, vm, vms, supportedDiskBusTypes }) => {
+    const [customDiskVerificationFailed, setCustomDiskVerificationFailed] = useState(false);
+    const [customDiskVerificationMessage, setCustomDiskVerificationMessage] = useState(null);
+    const [dialogError, setDialogError] = useState(null);
+    const [dialogErrorDetail, setDialogErrorDetail] = useState(null);
+    const [dialogLoading, setDialogLoading] = useState(true);
+    const [diskParams, setDiskParams] = useState({});
+    const [mode, setMode] = useState(isMediaInsertion ? CUSTOM_PATH : CREATE_NEW);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:371]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231116-154931-f2ab7bbc-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 57]
```diff
@@ -365,511 +359,505 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
-    }
-
-    validateParams() {
-        const validationFailed = {};
-
-        if (this.state.mode !== CUSTOM_PATH && !this.state.storagePoolName)
-            validationFailed.storagePool = _("Please choose a storage pool");
+        storagePoolGetAll({ connectionName: vm.connectionName })
+                .always(() => setDialogLoading(false))
+                .catch(exc => dialogErrorSet(_("Storage pools could not be fetched"), exc.message));
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:408]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231116-154931-f2ab7bbc-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 58]
```diff
@@ -365,511 +359,505 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
-    onValueChanged(key, value) {
-        let stateDelta = {};
-        const { storagePools, vm } = this.state;
+        setDiskParams(diskParams => ({ ...diskParams, busType: newBus }));
+    }, [diskParams.device, vm.disks]);
+
+    useEffect(() => {
+        // Initial state settings and follow up state updates after 'busType' is changed
+        const existingTargets = Object.getOwnPropertyNames(vm.disks);
+        const availableTarget = isMediaInsertion ? disk.target : getNextAvailableTarget(existingTargets, diskParams.busType);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:468]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231116-154931-f2ab7bbc-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 59]
```diff
@@ -365,511 +359,505 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
             // All pool types apart from 'disk' have either 'raw' or 'qcow2' format
-            if (currentPool && prevPool && ((currentPool.type == 'disk' && prevPool.type != 'disk') || (currentPool.type != 'disk' && prevPool.type == 'disk'))) {
-                // use onValueChange instead of setState in order to perform subsequent state change logic
-                this.onValueChanged('format', getDefaultVolumeFormat(value));
+            const prevPool = currentPoolRef.current;
+            if ((diskParams.storagePool?.type == 'disk' && prevPool?.type != 'disk') || (diskParams.storagePool?.type != 'disk' && prevPool?.type == 'disk')) {
+                prevPool.current = diskParams.storagePool;
+                setDiskParams(diskParams => ({
+                    ...diskParams,
+                    format: getDefaultVolumeFormat(diskParams.storagePool?.name),
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:484]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231116-154931-f2ab7bbc-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 60]
```diff
@@ -365,511 +359,505 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+    let defaultBody;
+    if (dialogLoading) {
+        defaultBody = (
+            <Bullseye>
+                <Spinner />
+            </Bullseye>
+        );
+    } else if (isMediaInsertion) {
+        defaultBody = (
+            <Form onSubmit={e => e.preventDefault()} isHorizontal>
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:594]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231116-154931-f2ab7bbc-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 61]
```diff
@@ -365,511 +359,505 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                <FormGroup fieldId={`${idPrefix}-source`}
+                           id={`${idPrefix}-source-group`}
+                           label={_("Source")} isInline hasNoPaddingTop>
+                    <Radio id={`${idPrefix}-custompath`}
+                           name="source"
+                           label={_("Custom path")}
+                           isChecked={mode === CUSTOM_PATH}
+                           onChange={() => onValueChanged('mode', CUSTOM_PATH)} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:602]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231116-154931-f2ab7bbc-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 62]
```diff
@@ -365,511 +359,505 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                                onValueChanged={onValueChanged}
+                                hideDeviceRow
+                                validationFailed={validationFailed} />
+                )}
+            </Form>
+        );
+    } else {
+        defaultBody = (
+            <>
+                <Form onSubmit={e => e.preventDefault()} isHorizontal>
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:630]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231116-154931-f2ab7bbc-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 63]
```diff
@@ -365,511 +359,505 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
     }
 
-    onInsertClicked() {
-        const Dialogs = this.context;
-        const close = Dialogs.close;
-        const { vm } = this.state;
-        const { disk } = this.props;
+    return (
+        <Modal position="top" variant="medium" id={`${idPrefix}-dialog-modal-window`} isOpen onClose={Dialogs.close}
+               title={isMediaInsertion ? _("Insert disc media") : _("Add disk")}
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:697]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231116-154931-f2ab7bbc-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 64]
```diff
@@ -365,511 +359,499 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+        cacheMode: 'default',
+        device: "disk",
+        file: "",
+        format: "",
+        serial: "",
+        size: 1,
+        unit: units.GiB.name,
+        volumeName: "",
+    });
+    const [mode, setMode] = useState(isMediaInsertion ? CUSTOM_PATH : CREATE_NEW);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:379]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-090529-31f818c6-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 65]
```diff
@@ -365,511 +359,499 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
         // Refresh storage volume list before displaying the dialog.
         // There are recently no Libvirt events for storage volumes and polling is ugly.
         // https://bugzilla.redhat.com/show_bug.cgi?id=1578836
-        storagePoolGetAll({ connectionName: this.props.vm.connectionName })
-                .then(() => this.setState({ dialogLoading: false, ...this.initialState }))
-                .catch(exc => this.dialogErrorSet(_("Storage pools could not be fetched"), exc.message));
-    }
+        storagePoolGetAll({ connectionName: vm.connectionName })
+                .always(() => setStoragePools(getVmStoragePools(vm.connectionName).sort(sortFunction)))
+                .catch(exc => dialogErrorSet(_("Storage pools could not be fetched"), exc.message));
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:404]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-090529-31f818c6-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 66]
```diff
@@ -365,511 +359,499 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
-        this.onValueChanged("device", deviceType);
+        setDiskParams(diskParams => ({ ...diskParams, busType: newBus }));
+    }, [diskParams.device, vm.disks]);
 
-        return stateDelta;
-    }
+    useEffect(() => {
+        // Initial state settings and follow up state updates after 'busType' is changed
+        const existingTargets = Object.getOwnPropertyNames(vm.disks);
+        const availableTarget = isMediaInsertion ? disk.target : getNextAvailableTarget(existingTargets, diskParams.busType);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:461]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-090529-31f818c6-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 67]
```diff
@@ -365,511 +359,499 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
             // All pool types apart from 'disk' have either 'raw' or 'qcow2' format
-            if (currentPool && prevPool && ((currentPool.type == 'disk' && prevPool.type != 'disk') || (currentPool.type != 'disk' && prevPool.type == 'disk'))) {
-                // use onValueChange instead of setState in order to perform subsequent state change logic
-                this.onValueChanged('format', getDefaultVolumeFormat(value));
+            const prevPool = currentPoolRef.current;
+            if ((diskParams.storagePool?.type == 'disk' && prevPool?.type != 'disk') || (diskParams.storagePool?.type != 'disk' && prevPool?.type == 'disk')) {
+                prevPool.current = diskParams.storagePool;
+                setDiskParams(diskParams => ({
+                    ...diskParams,
+                    format: getDefaultVolumeFormat(diskParams.storagePool?.name),
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:477]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-090529-31f818c6-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 68]
```diff
@@ -365,511 +359,499 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+    let defaultBody;
+    if (storagePools === undefined || diskParams.storagePool === undefined) {
+        defaultBody = (
+            <Bullseye>
+                <Spinner />
+            </Bullseye>
+        );
+    } else if (isMediaInsertion) {
+        defaultBody = (
+            <Form onSubmit={e => e.preventDefault()} isHorizontal>
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:587]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-090529-31f818c6-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 69]
```diff
@@ -365,511 +359,499 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                <FormGroup fieldId={`${idPrefix}-source`}
+                           id={`${idPrefix}-source-group`}
+                           label={_("Source")} isInline hasNoPaddingTop>
+                    <Radio id={`${idPrefix}-custompath`}
+                           name="source"
+                           label={_("Custom path")}
+                           isChecked={mode === CUSTOM_PATH}
+                           onChange={() => onValueChanged('mode', CUSTOM_PATH)} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:595]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-090529-31f818c6-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 70]
```diff
@@ -365,511 +359,499 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                                onValueChanged={onValueChanged}
+                                hideDeviceRow
+                                validationFailed={validationFailed} />
+                )}
+            </Form>
+        );
+    } else {
+        defaultBody = (
+            <>
+                <Form onSubmit={e => e.preventDefault()} isHorizontal>
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:623]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-090529-31f818c6-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 71]
```diff
@@ -365,511 +359,499 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                    <FormGroup fieldId={`${idPrefix}-source`}
+                               id={`${idPrefix}-source-group`}
+                               label={_("Source")} isInline hasNoPaddingTop>
+                        <Radio id={`${idPrefix}-createnew`}
+                               name="source"
+                               label={_("Create new")}
+                               isChecked={mode === CREATE_NEW}
+                               onChange={() => onValueChanged('mode', CREATE_NEW)} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:631]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-090529-31f818c6-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 72]
```diff
@@ -365,511 +359,499 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
     }
 
-    onInsertClicked() {
-        const Dialogs = this.context;
-        const close = Dialogs.close;
-        const { vm } = this.state;
-        const { disk } = this.props;
+    return (
+        <Modal position="top" variant="medium" id={`${idPrefix}-dialog-modal-window`} isOpen onClose={Dialogs.close}
+               title={isMediaInsertion ? _("Insert disc media") : _("Add disk")}
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:690]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-090529-31f818c6-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 73]
```diff
@@ -365,511 +359,499 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                    if (mode !== CUSTOM_PATH && volume.format === "raw" && isVolumeUsed[diskParams.existingVolumeName]) {
+                        isVolumeUsed[diskParams.existingVolumeName].forEach(vmName => {
                             const vm = vms.find(vm => vm.name === vmName);
-                            const diskTarget = getStorageVolumeDiskTarget(vm, storagePool, this.state.existingVolumeName);
+                            const diskTarget = getStorageVolumeDiskTarget(vm, storagePool, diskParams.existingVolumeName);
 
                             promises.push(
                                 domainUpdateDiskAttributes({ connectionName: vm.connectionName, objPath: vm.id, readonly: false, shareable: true, target: diskTarget })
-                                        .catch(exc => this.dialogErrorSet(_("Disk settings could not be saved"), exc.message))
+                                        .catch(exc => dialogErrorSet(_("Disk settings could not be saved"), exc.message))
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:808]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-090529-31f818c6-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 74]
```diff
@@ -365,511 +359,499 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+    return (
+        <>
+            <Button id={`${idPrefix}-dialog-add`}
+                    variant='primary'
+                    isLoading={addDiskInProgress || verificationInProgress}
+                    isDisabled={addDiskInProgress || verificationInProgress || dialogLoading ||
+                                (storagePools.length == 0 && mode != CUSTOM_PATH) ||
+                                (validate && Object.keys(validationFailed).length > 0)}
+                    onClick={onClick}>
+                {isMediaInsertion ? _("Insert") : _("Add")}
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:850]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-090529-31f818c6-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 75]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+        cacheMode: 'default',
+        device: "disk",
+        file: "",
+        format: "",
+        serial: "",
+        size: 1,
+        unit: units.GiB.name,
+        volumeName: "",
+    });
+    const [mode, setMode] = useState(isMediaInsertion ? CUSTOM_PATH : CREATE_NEW);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:379]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-111251-01255e48-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 76]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
-                .catch(exc => this.dialogErrorSet(_("Storage pools could not be fetched"), exc.message));
-    }
-
-    validateParams() {
-        const validationFailed = {};
+        storagePoolGetAll({ connectionName: vm.connectionName })
+                .always(() => {
+                    setStoragePools(getVmStoragePools(vm.connectionName).sort(sortFunction));
+                })
+                .catch(exc => dialogErrorSet(_("Storage pools could not be fetched"), exc.message));
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:406]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-111251-01255e48-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 77]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
-        this.onValueChanged("device", deviceType);
+        setDiskParams(diskParams => ({ ...diskParams, busType: newBus }));
+    }, [diskParams.device, vm.disks]);
 
-        return stateDelta;
-    }
+    useEffect(() => {
+        // Initial state settings and follow up state updates after 'busType' is changed
+        const existingTargets = Object.getOwnPropertyNames(vm.disks);
+        const availableTarget = isMediaInsertion ? disk.target : getNextAvailableTarget(existingTargets, diskParams.busType);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:463]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-111251-01255e48-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 78]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
             // All pool types apart from 'disk' have either 'raw' or 'qcow2' format
-            if (currentPool && prevPool && ((currentPool.type == 'disk' && prevPool.type != 'disk') || (currentPool.type != 'disk' && prevPool.type == 'disk'))) {
-                // use onValueChange instead of setState in order to perform subsequent state change logic
-                this.onValueChanged('format', getDefaultVolumeFormat(value));
+            const prevPool = currentPoolRef.current;
+            if ((diskParams.storagePool?.type == 'disk' && prevPool?.type != 'disk') || (diskParams.storagePool?.type != 'disk' && prevPool?.type == 'disk')) {
+                prevPool.current = diskParams.storagePool;
+                setDiskParams(diskParams => ({
+                    ...diskParams,
+                    format: getDefaultVolumeFormat(diskParams.storagePool?.name),
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:479]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-111251-01255e48-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 79]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+    const dialogLoading = storagePools === undefined;
+    if (dialogLoading) {
+        defaultBody = (
+            <Bullseye>
+                <Spinner />
+            </Bullseye>
+        );
+    } else if (isMediaInsertion) {
+        defaultBody = (
+            <Form onSubmit={e => e.preventDefault()} isHorizontal>
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:590]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-111251-01255e48-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 80]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                <FormGroup fieldId={`${idPrefix}-source`}
+                           id={`${idPrefix}-source-group`}
+                           label={_("Source")} isInline hasNoPaddingTop>
+                    <Radio id={`${idPrefix}-custompath`}
+                           name="source"
+                           label={_("Custom path")}
+                           isChecked={mode === CUSTOM_PATH}
+                           onChange={() => onValueChanged('mode', CUSTOM_PATH)} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:598]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-111251-01255e48-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 81]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                                onValueChanged={onValueChanged}
+                                hideDeviceRow
+                                validationFailed={validationFailed} />
+                )}
+            </Form>
+        );
+    } else {
+        defaultBody = (
+            <>
+                <Form onSubmit={e => e.preventDefault()} isHorizontal>
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:626]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-111251-01255e48-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 82]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
     }
 
-    onInsertClicked() {
-        const Dialogs = this.context;
-        const close = Dialogs.close;
-        const { vm } = this.state;
-        const { disk } = this.props;
+    return (
+        <Modal position="top" variant="medium" id={`${idPrefix}-dialog-modal-window`} isOpen onClose={Dialogs.close}
+               title={isMediaInsertion ? _("Insert disc media") : _("Add disk")}
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:693]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-111251-01255e48-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 83]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                    if (mode !== CUSTOM_PATH && volume.format === "raw" && isVolumeUsed[diskParams.existingVolumeName]) {
+                        isVolumeUsed[diskParams.existingVolumeName].forEach(vmName => {
                             const vm = vms.find(vm => vm.name === vmName);
-                            const diskTarget = getStorageVolumeDiskTarget(vm, storagePool, this.state.existingVolumeName);
+                            const diskTarget = getStorageVolumeDiskTarget(vm, storagePool, diskParams.existingVolumeName);
 
                             promises.push(
                                 domainUpdateDiskAttributes({ connectionName: vm.connectionName, objPath: vm.id, readonly: false, shareable: true, target: diskTarget })
-                                        .catch(exc => this.dialogErrorSet(_("Disk settings could not be saved"), exc.message))
+                                        .catch(exc => dialogErrorSet(_("Disk settings could not be saved"), exc.message))
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:807]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-111251-01255e48-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 84]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+    return (
+        <>
+            <Button id={`${idPrefix}-dialog-add`}
+                    variant='primary'
+                    isLoading={addDiskInProgress || verificationInProgress}
+                    isDisabled={addDiskInProgress || verificationInProgress || dialogLoading ||
+                                (storagePools.length == 0 && mode != CUSTOM_PATH) ||
+                                (validate && Object.keys(validationFailed).length > 0)}
+                    onClick={onClick}>
+                {isMediaInsertion ? _("Insert") : _("Add")}
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:849]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-111251-01255e48-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: test/check-machines-disks [hunk 85]
```diff
@@ -553,8 +551,7 @@ class TestMachinesDisks(VirtualMachinesCase):
                                                     ignore=[self.pixel_test_ignore] if self.pixel_test_ignore else [],
                                                     skip_layouts=["rtl"])
 
-            if not self.skip_add:
-                self.add_disk()
```
Comment (martinpitt) [inline test/check-machines-disks:557]: Why was this dropped?

**Review by martinpitt — COMMENTED** [review]
Awesome work, thank you so much! To validate this, could you please remove the 6 lines in https://github.com/cockpit-project/cockpit-machines/blob/f30caa3e523b1f64280d0cf61f6e16c63f0c2fcc/test/machineslib.py#L435 and give that a run on /devel ? If it succeeds, then this can add "Fixes #1272, #1273, #1275 . Even if it fixes just some of these, that's already progress, and then fixing the remaining ones should be much easier with this refactor.

File: test/check-machines-disks (hunk 85 above)
Comment (KKoukiou) [reply test/check-machines-disks:557]: See commit message:
```
    Two small behavior changes were introduced:
    First, on the validation of the input form. Previously the 'custom path'
    error was introduced also before 'add' was clicked. Now, this behaves like all other form fields,
    and validates on user's first 'Add' click.
```

So skip_add is not needed anymore, all the validation happens after the user clicks "Add" for first time. This change I did for consistently handling all verification errors and not have special cases there. I can revert if needed.

Comment (martinpitt) [reply test/check-machines-disks:557]: Perfect, thanks! No no, I'm all for removing special cases, I was just wondering.

**Comment by martinpitt** [comment]
OK, so that [doesn't fix](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-122027-f0bc3701-fedora-39-devel/log.html)  #1273, but fixing that should be much easier with the untangled rewrite. Thanks! I'll squash the two top commits together and add the two other fixes#.

**Review by martinpitt — DISMISSED** [review]
Tests are still running, but please land if/when it goes green. Thanks again! :hugs:

File: src/components/vm/disks/diskAdd.jsx (hunk 75 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:379]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-123758-a6ff1cb9-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 76 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:406]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-123758-a6ff1cb9-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 77 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:463]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-123758-a6ff1cb9-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 79 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:590]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-123758-a6ff1cb9-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 80 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:598]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-123758-a6ff1cb9-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 81 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:626]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-123758-a6ff1cb9-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 82 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:693]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-123758-a6ff1cb9-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 83 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:807]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-123758-a6ff1cb9-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 84 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:849]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-123758-a6ff1cb9-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

**Review by martinpitt — APPROVED** [review]
Put back the ignore pattern for the volume size

File: src/components/vm/disks/diskAdd.jsx (hunk 75 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:379]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 76 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:406]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 77 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:463]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 86]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+    }, [diskParams.device, vm.disks]);
 
-        return stateDelta;
-    }
+    useEffect(() => {
+        // Initial state settings and follow up state updates after 'busType' is changed
+        const existingTargets = Object.getOwnPropertyNames(vm.disks);
+        const availableTarget = isMediaInsertion ? disk.target : getNextAvailableTarget(existingTargets, diskParams.busType);
+        setDiskParams(diskParams => ({ ...diskParams, target: availableTarget }));
+    }, [vm.disks, disk?.target, diskParams.busType, isMediaInsertion]);
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:465]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 78 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:479]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 87]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                </FormGroup>
+                {mode === USE_EXISTING && (
+                    <UseExistingDisk idPrefix={`${idPrefix}-existing`}
+                                     onValueChanged={onValueChanged}
+                                     storagePoolName={storagePoolName}
+                                     existingVolumeName={diskParams.existingVolumeName}
+                                     validationFailed={validationFailed}
+                                     vmStoragePools={storagePools}
+                                     vms={vms}
+                                     vm={vm} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:613]: These 26 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 88]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                )}
+                {mode === CUSTOM_PATH && (
+                    <CustomPath idPrefix={idPrefix}
+                                onValueChanged={onValueChanged}
+                                hideDeviceRow
+                                validationFailed={validationFailed} />
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:619]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 89]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+                )}
+            </Form>
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:621]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 81 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:626]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 82 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:693]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 90]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+    validationFailed,
+    verificationInProgress,
+    vm,
+    vms,
+}) => {
+    const [addDiskInProgress, setAddDiskInProgress] = useState(false);
+    const Dialogs = useDialogs();
 
-        this.setState({ addDiskInProgress: true, validate: false });
+    const onInsertClicked = () => {
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:738]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 91]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
-            target: disk.target,
-            diskType: this.state.mode === CUSTOM_PATH ? "file" : "volume",
-            file: this.state.file,
-            poolName: this.state.storagePoolName,
-            volumeName: this.state.existingVolumeName,
+            target: diskParams.target,
+            diskType: mode === CUSTOM_PATH ? "file" : "volume",
+            file: diskParams.file,
+            poolName: storagePoolName,
+            volumeName: diskParams.existingVolumeName,
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:746]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 83 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:807]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx [hunk 92]
```diff
@@ -365,511 +359,498 @@ const CustomPath = ({ idPrefix, onValueChanged, device, validationFailed, hideDe
...
+        if (Object.getOwnPropertyNames(validationFailed).length > 0) {
+            setAddDiskInProgress(false);
+            return;
+        }
+
+        setAddDiskInProgress(true);
 
+        return (
+            isMediaInsertion
+                ? onInsertClicked()
```
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:827]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 84 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:849]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/vmDiskColumns.jsx [hunk 93]
```diff
@@ -167,7 +167,7 @@ export const DiskActions = ({ vm, vms, disk, supportedDiskBusTypes, idPrefixRow,
     const Dialogs = useDialogs();
 
     function openMediaInsertionDialog() {
-        Dialogs.show(<AddDiskModalBody idPrefix={idPrefixRow + "-insert-dialog"}
+        Dialogs.show(<AddDiskModalBody idPrefix={idPrefixRow + "-insert-dialog-adddisk"}
```
Comment (cockpituous) [inline src/components/vm/disks/vmDiskColumns.jsx:170]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231117-134447-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

**Comment by martinpitt** [comment]
Tests are an absolute nightmare here, and that is already after a retry. Stuff like
```
# testExternalConsole (__main__.TestMachinesConsoles.testExternalConsole)
ERROR    Error: --disk /var/lib/libvirt/images/subVmTest1-2.img: Could not define storage pool: cannot create config directory /etc/libvirt/storage: No such file or directory
```
Maybe the add disk dialog 3x affected retries spot some tests which don't properly clean up after themselves or so?

**Comment by martinpitt** [comment]
I think the `TestMachinesDisks.testAddDiskPool` failure on [c9s](https://artifacts.dev.testing-farm.io/2bcbfda0-c48e-4da4-bd8f-c57627c11c88/) and [f39](https://artifacts.dev.testing-farm.io/d766ce22-af8b-4159-a811-f60403b3199f/) are new regressions.

File: src/components/vm/disks/diskAdd.jsx (hunk 75 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:379]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231120-122732-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 76 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:406]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231120-122732-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 77 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:463]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231120-122732-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 78 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:479]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231120-122732-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 79 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:590]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231120-122732-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 80 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:598]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231120-122732-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 81 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:626]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231120-122732-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 82 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:693]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231120-122732-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 83 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:807]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231120-122732-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: src/components/vm/disks/diskAdd.jsx (hunk 84 above)
Comment (cockpituous) [inline src/components/vm/disks/diskAdd.jsx:849]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-1303-20231120-122732-13cb53e1-fedora-39-devel//Coverage/lcov/github-pr.diff.gcov.html)
